# Generated by Django 6.0.6 on 2026-06-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='category',
            field=models.CharField(choices=[('ui', 'UI'), ('backend', 'Backend'), ('database', 'Database'), ('performance', 'Performance'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='bug',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
    ]
