# Generated by Django 6.0.6 on 2026-06-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_bug_category_bug_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='category',
            field=models.CharField(choices=[('ui', 'UI'), ('backend', 'Backend'), ('database', 'Database'), ('performance', 'Performance'), ('security', 'Security'), ('other', 'Other'), ('auth', 'Authentication')], default='other', max_length=20),
        ),
    ]
